// <auto-generated>
// This source code was auto-generated by SystemInstallerGenerator.cs
// </auto-generated>

using AnotherECS.Core;

namespace AnotherECS.Gen.Project
{
    public static class SystemInstaller
    {
        private static bool _isNoInstalled = true;

        public static void Install()
        {
            if (_isNoInstalled)
            {
                _isNoInstalled = false;
                InstallInternal();
            }
        }

        private static void InstallInternal()
        {
            SystemGlobalRegister.Install<AnotherECS.Unity.Debug.Diagnostic.CheatFeature>(0, null);
            SystemGlobalRegister.Install<AnotherECS.Physics.PhysicsSystem>(1, null);
            SystemGlobalRegister.Install<AnotherECS.Random.RandomFeature>(2, null);
            SystemGlobalRegister.Install<AnotherECS.Unity.Debug.Diagnostic.CheatSystem>(3, null);
            SystemGlobalRegister.Install<AnotherECS.Core.SystemGroup>(4, null);
            SystemGlobalRegister.Install<Test0System>(5, null);
            SystemGlobalRegister.Install<AnotherECS.Unity.Jobs.JobsModule>(6, null);
            SystemGlobalRegister.Install<AnotherECS.Unity.Debug.Diagnostic.DiagnosticModule>(7, null);
            SystemGlobalRegister.Install<AnotherECS.Unity.Views.UnityViewModule>(8, null);

            SystemAutoAttachGlobalRegister.Install<AnotherECS.Unity.Jobs.JobsModule>();

        }
    }
}

